# Generated by Django 2.2.1 on 2019-11-06 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reporter',
            options={'verbose_name': '作者', 'verbose_name_plural': '作者'},
        ),
        migrations.AddField(
            model_name='reporter',
            name='body_size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], default='M', max_length=1, verbose_name='身材尺寸'),
        ),
        migrations.AlterField(
            model_name='reporter',
            name='full_name',
            field=models.CharField(max_length=70, verbose_name='作者全名'),
        ),
    ]
