# Generated by Django 2.2.6 on 2019-11-06 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20191106_1438'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['pub_date'], 'verbose_name': '文章', 'verbose_name_plural': '文章'},
        ),
    ]
